ALTER SEQUENCE TRVL_CLIENT_ID_SEQ INCREMENT BY 100;
SELECT TRVL_CLIENT_ID_SEQ.nextval from dual;
ALTER SEQUENCE TRVL_CLIENT_ID_SEQ INCREMENT BY 1;

ALTER SEQUENCE TRVL_DISCOUNT_ID_SEQ INCREMENT BY 100;
SELECT TRVL_DISCOUNT_ID_SEQ.nextval from dual;
ALTER SEQUENCE TRVL_DISCOUNT_ID_SEQ INCREMENT BY 1;

ALTER SEQUENCE TRVL_EMPLOYEE_ID_SEQ INCREMENT BY 100;
SELECT TRVL_EMPLOYEE_ID_SEQ.nextval from dual;
ALTER SEQUENCE TRVL_EMPLOYEE_ID_SEQ INCREMENT BY 1;

ALTER SEQUENCE TRVL_HOTELS_ID_SEQ INCREMENT BY 100;
SELECT TRVL_HOTELS_ID_SEQ.nextval from dual;
ALTER SEQUENCE TRVL_HOTELS_ID_SEQ INCREMENT BY 1;

ALTER SEQUENCE TRVL_NUTRITION_ID_SEQ INCREMENT BY 100;
SELECT TRVL_NUTRITION_ID_SEQ.nextval from dual;
ALTER SEQUENCE TRVL_NUTRITION_ID_SEQ INCREMENT BY 1;

ALTER SEQUENCE TRVL_REFUNDS_ID_SEQ INCREMENT BY 100;
SELECT TRVL_REFUNDS_ID_SEQ.nextval from dual;
ALTER SEQUENCE TRVL_REFUNDS_ID_SEQ INCREMENT BY 1;

ALTER SEQUENCE TRVL_SALES_ID_SEQ INCREMENT BY 100;
SELECT TRVL_SALES_ID_SEQ.nextval from dual;
ALTER SEQUENCE TRVL_SALES_ID_SEQ INCREMENT BY 1;

ALTER SEQUENCE TRVL_TOURS_ID_SEQ INCREMENT BY 100;
SELECT TRVL_TOURS_ID_SEQ.nextval from dual;
ALTER SEQUENCE TRVL_TOURS_ID_SEQ INCREMENT BY 1;

ALTER SEQUENCE TRVL_TOUR_TYPES_ID_SEQ INCREMENT BY 100;
SELECT TRVL_TOUR_TYPES_ID_SEQ.nextval from dual;
ALTER SEQUENCE TRVL_TOUR_TYPES_ID_SEQ INCREMENT BY 1;